working in-memory app created, all tests pass
davis-gr/flight-planner-app pull request #1
Opened 2022-11-17 10:12 UTC by davis-gr

2022-11-20 10:55 UTC, janistumpelis requested changes
Kopumā ļoti labi, paldies!

2022-11-20 10:55 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/airports/AirportRepository.java
> +        return airportList.stream().filter(a -> a.getCity().toLowerCase().startsWith(search) || a.getCountry().toLowerCase().startsWith(search) || a.getAirport().toLowerCase().startsWith(search)).fin
Varbūt labāk `contains` nevis `startsWith`?

2022-11-20 10:55 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/airports/AirportRepository.java
> +    public boolean equals(Object o) {
Equals un HashCode metodes Spring Bean nav nepieciešamas. Jo teorētiski būtu jāpastāv tikai vienai šīs repository instancei tāpēc nekādai salīdzināšanai u.tml nevajadzētu būt.

2022-11-20 10:55 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/airports/objects/Airport.java
> +    @NotNull
Vai NotBlank sevī neietver arī faktiski NotNull? 🤔

2022-11-20 10:55 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/api/SearchFlightsRequest.java
> +    public boolean equals(Object o) {
Nu te arī it kā pēc equals un hashCode neprasās, jo droši vien nekad nesalīdzināsi divus search request, bet var arī atstāt.

2022-11-20 10:55 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/config/SecurityConfiguration.java
> +                .csrf().disable() //disables CSRF protection
Komentārus labāk noņem.

2022-11-20 10:55 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/flights/FlightService.java
> +        } catch (NullPointerException e) {
No kurienes te var rasties NPE?

2022-11-20 10:55 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/flights/FlightService.java
> +            if (flightRepository.getFlightList().size() > 0) {
Šis IF faktiski nav nepieciešams, jo for each loops nemaz nepildīsies, ja saraksts būs tukšs.

2022-11-20 10:55 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/flights/FlightService.java
> +                    if (anyFlight.getFrom().equals(flight.getFrom()) && anyFlight.getTo().equals(flight.getTo()) && anyFlight.getCarrier().equals(flight.getCarrier())
Varbūt to salīdzināšanu iznest atsevišķa metodē? To metodi var pat uztaisīt iekš paša Flight un nosaukt, piemēram, areFlightsEqual

2022-11-20 10:55 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/flights/FlightRepository.java
> +        return flightList.stream().filter(f -> Objects.equals(f.getId(), flightId)).toList().get(0);
Kāpēc ne vienkārši `f.getId().equals(flightId)` ?

2022-11-20 10:55 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/flights/FlightRepository.java
> +        return flightList.stream().filter(f -> Objects.equals(f.getId(), flightId)).toList().get(0);
Kā arī - kā jau pats esi uzkodējis - šī metodē var mest kļūdu, ja saraksts ir tukšs. Bet varbūt tad labāk šai metodei atgriezt Optional (man liekas te var izmantot Stream metodi findFirst)? Tad kods būs drošāks. :)

2022-11-21 15:36 UTC, davis-gr commented
Paldies, izlaboju visus komentārus!

2022-11-26 06:50 UTC, janistumpelis approved these changes

2022-11-29 07:56 UTC, merged